In [1]:
import numpy as np

In [2]:
arr = np.arange(0,11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
# Getting a value at an index
arr[8]

8

In [5]:
# in a range
arr[0:5]

array([0, 1, 2, 3, 4])

In [6]:
# Broadcasting
arr[0:5] = 100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [7]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
slice_of_arr = arr[0:6]
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [9]:
# Change the slice 
slice_of_arr[:] = 99 

In [10]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [11]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [12]:
#Now note the changes also occur in our original array!
#Data is not copied, it's a view of the original array!
#This avoids memory problems!
# So,we use a copy
arr_copy = arr.copy()
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [16]:
#Indexing in 2d array
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [17]:
# indexing row
arr_2d[1]

array([20, 25, 30])

In [18]:
# getting individual element
arr_2d[1][0]

20

In [20]:
arr_2d[1,0]

20

In [21]:
# 2d array slicing
# shape(2,2) from top right corner
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [22]:
# shape_bottom_row
arr_2d[2]

array([35, 40, 45])

In [23]:
# FANCY INDEXING
#Fancy indexing allows you to select entire rows or columns out of order
#to show this, let's quickly build out a numpy array
arr2d = np.zeros((10,10))

In [24]:
arr_length = arr2d.shape[1]

In [25]:
for i in range(arr_length):
    arr2d[i] = i
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [28]:
arr2d[[2,4,6,8]]

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.]])

In [29]:
#selection based off of comparison operators.
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [30]:
arr>4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [31]:
bool_arr = arr>4

In [32]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [33]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [34]:
arr[arr>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])