In [1]:
import numpy as np

In [2]:
#Creating numpy arrays 
my_list = [6,3,7]
my_list

[6, 3, 7]

In [3]:
np.array(my_list)

array([6, 3, 7])

In [4]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]

In [5]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
# Built-in methods to create arrays
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [8]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [9]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [11]:
# Return Evenly spaced integers over a specified interval
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [12]:
# IDENTITY MATRIX
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [17]:
np.random.rand(2,2)

array([[0.88316963, 0.59053276],
       [0.4083786 , 0.90432475]])

In [18]:
#Return a sample fron the'Standard Normal' Distribution.
np.random.randn(2)

array([0.20475546, 0.3445302 ])

In [19]:
np.random.randn(5,5)

array([[-0.88989859,  1.19410801,  1.03884503, -0.2859866 , -1.08169696],
       [-0.67299805, -0.10641373,  1.43298675,  0.45965337,  0.18662528],
       [-1.18419143, -0.33015627,  0.22424691,  0.53501619, -0.37927982],
       [-1.08133595, -0.66648823, -0.20761525,  0.84889649,  0.09310822],
       [ 0.34656803,  0.11551013, -0.14732758, -0.65443498,  0.26987352]])

In [20]:
#Return Random integers from low(inclusive) to high(Exclusive)
np.random.randint(1,100)

38

In [22]:
np.random.randint(1,100,(5,5))

array([[61, 72, 67,  6, 48],
       [16, 41, 27, 25, 70],
       [85,  1, 58, 62, 36],
       [39, 96, 60, 63, 30],
       [ 4, 66, 71, 55,  5]])

In [23]:
# RESHAPING ARRAYS
arr = np.arange(25)
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [24]:
ranar = np.random.randint(1,100,10)

In [25]:
ranar

array([57, 33, 97, 41, 84, 69, 33, 28,  3, 60])

In [26]:
#MAX,MIN,ARGMAX,ARGMIN
ranar.max()

97

In [27]:
ranar.min()

3

In [28]:
ranar.argmax()

2

In [29]:
ranar.argmin()

8

In [30]:
# SHAPE IS AN ATTRIBUTE THAT ARRAYS HAVE NOT A METHOD
arr.shape

(25,)

In [33]:
a = arr.reshape(1,25)

In [34]:
a.shape

(1, 25)

In [35]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])